apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: demo
  labels:
    app: hello
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
